-- MySQL Script generated by MySQL Workbench
-- Tue 05 Nov 2019 12:00:46 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema iweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iweb` DEFAULT CHARACTER SET utf8 ;
USE `iweb` ;

-- -----------------------------------------------------
-- Table `iweb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`EntidadEMT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb`.`EntidadEMT` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb`.`Comentario` (
  `usuario_id` INT NOT NULL,
  `entidadEMT_id` INT NOT NULL,
  `texto` VARCHAR(250) NULL,
  `imagen` VARCHAR(250) NULL,
  INDEX `fk_Comentario_Usuario_idx` (`usuario_id` ASC),
  PRIMARY KEY (`usuario_id`, `entidadEMT_id`),
  INDEX `fk_Comentario_entidadEMT1_idx` (`entidadEMT_id` ASC),
  CONSTRAINT `fk_Comentario_Usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `iweb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_entidadEMT1`
    FOREIGN KEY (`entidadEMT_id`)
    REFERENCES `iweb`.`EntidadEMT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`Parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb`.`Parada` (
  `entidadEMT_id` INT NOT NULL,
  INDEX `fk_Parada_entidadEMT1_idx` (`entidadEMT_id` ASC),
  PRIMARY KEY (`entidadEMT_id`),
  CONSTRAINT `fk_Parada_entidadEMT1`
    FOREIGN KEY (`entidadEMT_id`)
    REFERENCES `iweb`.`EntidadEMT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`Autobus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iweb`.`Autobus` (
  `entidadEMT_id` INT NOT NULL,
  INDEX `fk_Autobus_entidadEMT1_idx` (`entidadEMT_id` ASC),
  PRIMARY KEY (`entidadEMT_id`),
  CONSTRAINT `fk_Autobus_entidadEMT1`
    FOREIGN KEY (`entidadEMT_id`)
    REFERENCES `iweb`.`EntidadEMT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
