-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 17:39:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema iweb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iweb` ;

-- -----------------------------------------------------
-- Schema iweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iweb` DEFAULT CHARACTER SET utf8 ;
USE `iweb` ;

-- -----------------------------------------------------
-- Table `iweb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iweb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `iweb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iweb`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iweb`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `iweb`.`Comentario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `codigoEMT` VARCHAR(100) NOT NULL,
  `texto` VARCHAR(250) NULL,
  `imagen` VARCHAR(250) NULL,
  INDEX `fk_Comentario_Usuario_idx` (`usuario_id` ASC),
  PRIMARY KEY (`id`, `usuario_id`, `codigoEMT`),
  CONSTRAINT `fk_Comentario_Usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `iweb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
